Test 5

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -40,7 +40,7 @@ jobs:
         id: black
         run: |
           source .venv/bin/activate
-          black --check . 2>&1 | tee black_output.txt || (echo "failed" > black_failed.txt; echo "BLACK_FAIL=true" >> $GITHUB_ENV)
+          black --check . 2>&1 | tee black_output.txt || (echo "failed" > black_failed.txt; echo "::set-output name=BLACK_FAIL::true")
 
       - name: Upload Black Output
         if: always()
@@ -50,7 +50,7 @@ jobs:
           path: black_output.txt
 
       - name: Fail if Black Failed
-        if: env.BLACK_FAIL == 'true'
+        if: steps.black.outputs.BLACK_FAIL == 'true'
         run: exit 1
 
   Errors:
@@ -79,7 +79,7 @@ jobs:
         id: ruff
         run: |
           source .venv/bin/activate
-          ruff check . 2>&1 | tee ruff_output.txt || (echo "failed" > ruff_failed.txt; echo "RUFF_FAIL=true" >> $GITHUB_ENV)
+          ruff check . 2>&1 | tee ruff_output.txt || (echo "failed" > ruff_failed.txt; echo "::set-output name=RUFF_FAIL::true")
 
       - name: Upload Ruff Output
         if: always()
@@ -89,7 +89,7 @@ jobs:
           path: ruff_output.txt
 
       - name: Fail if Ruff Failed
-        if: env.RUFF_FAIL == 'true'
+        if: steps.ruff.outputs.RUFF_FAIL == 'true'
         run: exit 1
 
   Tests:
@@ -118,7 +118,7 @@ jobs:
         id: pytest
         run: |
           source .venv/bin/activate
-          coverage run -m pytest -v -s 2>&1 | tee pytest_output.txt || (echo "failed" > pytest_failed.txt; echo "PYTEST_FAIL=true" >> $GITHUB_ENV)
+          coverage run -m pytest -v -s 2>&1 | tee pytest_output.txt || (echo "failed" > pytest_failed.txt; echo "::set-output name=PYTEST_FAIL::true")
 
       - name: Generate Coverage Report
         run: |
@@ -140,7 +140,7 @@ jobs:
           path: coverage_output.txt
 
       - name: Fail if Pytest Failed
-        if: env.PYTEST_FAIL == 'true'
+        if: steps.pytest.outputs.PYTEST_FAIL == 'true'
         run: exit 1
 
   Summary:
